export const MESSAGE_INPUT_CHANGED = 'MESSAGE_INPUT_CHANGED';
export const NAME_INPUT_CHANGED = 'NAME_INPUT_CHANGED';
export const SEND_BUTTON_CLICKED = 'SEND_BUTTON_CLICKED';
export const SERVER_PUSHED_NEW_MESSAGE = 'SERVER_PUSHED_NEW_MESSAGE';
export const CLIENT_PUSHED_NEW_MESSAGE = 'CLIENT_PUSHED_NEW_MESSAGE';
